#!/bin/bash

: "${MESOS_NATIVE_JAVA_LIBRARY?MESOS_NATIVE_JAVA_LIBRARY not set}"
: "${HOME_MARATHON?HOME_MARATHON not set}"
: "${MASTER_MARATHON?MASTER_MARATHON not set}"
: "${ZOOKEEPER_MARATHON?ZOOKEEPER_MARATHON not set}"

$HOME_MARATHON/bin/start --master $MASTER_MARATHON --zk $ZOOKEEPER_MARATHON
